const CONTENT_TYPE = 'OFFERHIGHLIGHT'
const CARD_MARGIN_RIGHT = 20
const CARD_WIDTH_FHD = 1720 + CARD_MARGIN_RIGHT
const CARD_WIDTH_HD = 1145 + CARD_MARGIN_RIGHT
const CARDS_LEFT = 2
const CARDS_RIGHT = 5
const CARDS_THRESHOLD = 5
const PAGINATION_SIZE = 4
const MINIMUM_CARDS = 4
const RAIL_HEIGHT_FHD = 612
const RAIL_HEIGHT_HD = 408

const HIGHLIGHT_RAIL_CONSTANTS = {
  CONTENT_TYPE,
  CARD_MARGIN_RIGHT,
  CARD_WIDTH_FHD,
  CARD_WIDTH_HD,
  CARDS_LEFT,
  CARDS_RIGHT,
  CARDS_THRESHOLD,
  PAGINATION_SIZE,
  MINIMUM_CARDS,
  RAIL_HEIGHT_FHD,
  RAIL_HEIGHT_HD,
} as const

export default HIGHLIGHT_RAIL_CONSTANTS
